"""Non-IID client partitioning and label-distribution diagnostics."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder


def make_noniid_label_split_with_trick(
    y_train_array: np.ndarray,
    num_clients: int = 10,
    seed: int = 42,
    min_size_target: int = 500,
    max_retries: int = 1000,
) -> list[np.ndarray]:
    """Partition training indices by label using the notebook's Non-IID scheme."""
    unique_labels = np.unique(y_train_array)

    min_label_clients = max(1, int(0.10 * num_clients))
    max_label_clients = max(min_label_clients, int(0.80 * num_clients))

    best_indices: list[np.ndarray] | None = None
    best_min_size = -1

    for attempt in range(max_retries):
        current_attempt_rng = np.random.default_rng(seed + attempt)
        client_indices = [[] for _ in range(num_clients)]

        for class_id in unique_labels:
            label_positions = np.where(y_train_array == class_id)[0].copy()
            current_attempt_rng.shuffle(label_positions)
            total_samples = len(label_positions)

            k_clients = current_attempt_rng.integers(
                min_label_clients,
                max_label_clients + 1,
            )
            k_clients = min(k_clients, total_samples)
            chosen_clients = current_attempt_rng.choice(
                num_clients,
                size=k_clients,
                replace=False,
            )

            remaining = total_samples
            for i, client_id in enumerate(chosen_clients):
                if i == k_clients - 1:
                    count = remaining
                else:
                    min_prop = (1.0 / 10.0) * (1.0 / k_clients)
                    max_prop = 1.0 / k_clients
                    low = max(1, int(min_prop * total_samples))
                    high = max(low, int(max_prop * total_samples))
                    count = current_attempt_rng.integers(low, high + 1)

                start = total_samples - remaining
                client_indices[client_id].extend(
                    label_positions[start : start + count]
                )
                remaining -= count

        current_min_size = min(len(indices) for indices in client_indices)
        if current_min_size >= min_size_target:
            return [np.array(indices) for indices in client_indices]

        if current_min_size > best_min_size:
            best_min_size = current_min_size
            best_indices = [np.array(indices) for indices in client_indices]

    return best_indices


def build_client_label_distribution(
    client_indices: list[np.ndarray],
    y_train: np.ndarray,
    label_encoder: LabelEncoder,
) -> pd.DataFrame:
    """Build the per-client label-count table saved by the notebooks."""
    client_label_rows = []
    num_classes = len(label_encoder.classes_)

    for client_id, indices in enumerate(client_indices):
        counts = np.bincount(y_train[indices], minlength=num_classes)
        row = {
            "client_id": client_id,
            "total_samples": int(len(indices)),
        }
        for class_id, class_name in enumerate(label_encoder.classes_):
            row[str(class_name)] = int(counts[class_id])
        client_label_rows.append(row)

    return pd.DataFrame(client_label_rows)


def plot_client_label_distribution(
    client_indices: list[np.ndarray],
    y_train: np.ndarray,
    label_list: list[str],
    output_path: str | Path,
    show: bool = False,
) -> None:
    """Save the bubble chart generated by the preprocessing notebooks."""
    import matplotlib.patches as mpatches
    import matplotlib.pyplot as plt

    num_clients_plot = len(client_indices)
    client_ids = [f"C{client_id:02d}" for client_id in range(num_clients_plot)]
    classes = label_list
    num_cls = len(classes)
    num_classes = len(label_list)

    unique_pastel_colors = [
        "#ff0000",
        "#ff8700",
        "#ffbd00",
        "#fcf300",
        "#a1ff0a",
        "#0aff99",
        "#147df5",
        "#580aff",
        "#be0aff",
        "#be0aff",
        "#be0aff",
        "#be0aff",
        "#be0aff",
        "#ff7096",
    ]
    label_colors = [
        unique_pastel_colors[i % len(unique_pastel_colors)]
        for i in range(num_cls)
    ]

    all_counts_flat = []
    for indices in client_indices:
        counts = np.bincount(y_train[indices], minlength=num_classes)
        all_counts_flat.extend(counts.tolist())

    max_count = max((count for count in all_counts_flat if count > 0), default=1)
    fig_height = max(8, num_cls * 0.38)
    fig, ax = plt.subplots(
        figsize=(max(16, num_clients_plot * 0.55) + 3, fig_height)
    )

    ax.set_facecolor("#F8FAFC")
    fig.patch.set_facecolor("white")

    for label_idx, (class_name, color) in enumerate(zip(classes, label_colors)):
        for client_id, indices in enumerate(client_indices):
            counts = np.bincount(y_train[indices], minlength=num_classes)
            count = counts[label_idx]
            if count > 0:
                size = max(20, (count / max_count) * 2000)
                ax.scatter(
                    client_id,
                    label_idx,
                    s=size,
                    color=color,
                    alpha=0.9,
                    edgecolors="white",
                    linewidths=0.8,
                    zorder=3,
                )
            else:
                ax.scatter(
                    client_id,
                    label_idx,
                    s=10,
                    color="#E2E8F0",
                    alpha=0.5,
                    edgecolors="none",
                    zorder=2,
                )

    ax.set_yticks(range(num_cls))
    ax.set_yticklabels(classes, fontsize=9, fontfamily="monospace")
    ax.invert_yaxis()
    ax.set_xticks(range(num_clients_plot))
    ax.set_xticklabels(client_ids, fontsize=8.5, rotation=45, ha="right")
    ax.set_xlabel("Client ID", fontsize=12, labelpad=10)
    ax.set_title(
        "Label Distribution Across Clients",
        fontsize=14,
        pad=15,
        fontweight="bold",
    )
    ax.grid(
        True,
        which="both",
        linestyle="dashed",
        linewidth=0.7,
        color="#CBD5E1",
        zorder=1,
    )
    ax.set_axisbelow(True)

    legend_patches = [
        mpatches.Patch(
            facecolor=color,
            edgecolor="white",
            linewidth=1,
            label=class_name,
        )
        for class_name, color in zip(classes, label_colors)
    ]
    ax.legend(
        handles=legend_patches,
        title="Class Labels",
        bbox_to_anchor=(1.01, 1),
        loc="upper left",
        fontsize=9,
        title_fontsize=11,
        frameon=True,
        shadow=False,
    )

    fig.tight_layout()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    if show:
        plt.show()
    plt.close(fig)
